// In-browser challenge test harness. The engine compiles a program, not a test
// binary, so we add a generated main that hands the learner's Test functions to
// testing.Main with -test.v, then parse the verbose output per test case.
// The same functions parse real `go test -v` output in the content verifier,
// so engine and native results are compared with identical logic.
// Pure and erasable TypeScript (importable from Node).

export const HARNESS_FILE = "zz_harness.go";
export const LEARNER_FILE = "challenge.go";
export const TESTS_FILE = "challenge_test.go";

export function testNames(testSource: string): string[] {
  const names: string[] = [];
  for (const m of testSource.matchAll(/^func (Test[A-Z0-9_]\w*|Test)\(\s*\w+\s+\*testing\.T\s*\)/gm)) names.push(m[1]);
  return names;
}

export function buildHarness(testSources: string[]): string {
  const names = testSources.flatMap(testNames);
  if (names.length === 0) throw new Error("harness: no Test functions found");
  const table = names.map((n) => `\t\t{Name: ${JSON.stringify(n)}, F: ${n}},`).join("\n");
  return `// Code generated by Go Forge. DO NOT EDIT.

package main

import (
	__goforge_os "os"
	__goforge_regexp "regexp"
	__goforge_testing "testing"
)

func main() {
	__goforge_os.Args = []string{"challenge.test", "-test.v", "-test.count=1"}
	__goforge_testing.Main(__goforge_regexp.MatchString, []__goforge_testing.InternalTest{
${table}
	}, nil, nil)
}
`;
}

export type CaseStatus = "PASS" | "FAIL" | "SKIP";
export type CaseResult = { name: string; status: CaseStatus; output: string[] };

export type TestReport = {
  /** Every test (leaf case) passed and the process exited 0. */
  passed: boolean;
  /** Leaf results only: a parent test with subtests is represented by its subtests. */
  cases: CaseResult[];
  failedCases: string[];
  /** The run did not finish normally (panic, timeout, compile error) - cases may be incomplete. */
  incomplete: boolean;
};

export function parseTestOutput(stdout: string, exitCode: number): TestReport {
  const results = new Map<string, CaseResult>();
  const order: string[] = [];
  let current: string | null = null;
  const ensure = (name: string) => {
    if (!results.has(name)) {
      results.set(name, { name, status: "FAIL", output: [] });
      order.push(name);
    }
    return results.get(name)!;
  };
  const seenStatus = new Set<string>();

  for (const raw of stdout.replace(/\r\n/g, "\n").split("\n")) {
    const line = raw.trimStart();
    let m: RegExpMatchArray | null;
    if ((m = line.match(/^=== (?:RUN|CONT|NAME|PAUSE)\s+(\S+)/))) {
      current = m[1];
      ensure(current);
    } else if ((m = line.match(/^--- (PASS|FAIL|SKIP): (\S+)/))) {
      const r = ensure(m[2]);
      r.status = m[1] as CaseStatus;
      seenStatus.add(m[2]);
    } else if (current && raw.startsWith("    ") && line !== "") {
      ensure(current).output.push(line);
    }
  }

  const names = order;
  const isParent = (n: string) => names.some((o) => o.startsWith(n + "/"));
  const cases = names.filter((n) => !isParent(n)).map((n) => results.get(n)!);
  const incomplete = cases.length === 0 || cases.some((c) => !seenStatus.has(c.name)) || !/^(PASS|FAIL)$/m.test(stdout);
  const failedCases = cases.filter((c) => c.status === "FAIL").map((c) => c.name);
  return { passed: exitCode === 0 && !incomplete && failedCases.length === 0, cases, failedCases, incomplete };
}
