-- GENERATED by scripts/gen-seed.mjs from content/go/track.json. Do not edit.
begin;

insert into public.tracks (slug, title, "order") values ('go', 'Go from first principles', 1)
  on conflict (slug) do update set title = excluded.title, "order" = excluded."order";

insert into public.modules (track_id, slug, code, title, "order") select id, 'm0-compiled', 'M0', 'What "compiled" actually means', 0 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'go-run-vs-go-build', 'go run is not a benchmark', 0, array[]::text[], 'go/m0-compiled/go-run-vs-go-build' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm0-compiled'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'source-to-machine-code', 'Tokens, AST, types, SSA, machine code', 1, array[]::text[], 'go/m0-compiled/source-to-machine-code' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm0-compiled'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'runtime-in-every-binary', 'The runtime lives in your binary', 2, array[]::text[], 'go/m0-compiled/runtime-in-every-binary' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm0-compiled'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm1-types-values-memory', 'M1', 'Types, values, memory', 1 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'zero-values', 'Nothing is ever undefined', 0, array[]::text[], 'go/m1-types-values-memory/zero-values' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm1-types-values-memory'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'no-implicit-conversion', 'int + int64 does not compile', 1, array[]::text[], 'go/m1-types-values-memory/no-implicit-conversion' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm1-types-values-memory'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'integer-division', '7 / 2 and -7 / 2', 2, array[]::text[], 'go/m1-types-values-memory/integer-division' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm1-types-values-memory'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'bytes-runes-strings', 'len("héllo") is not 5', 3, array[]::text[], 'go/m1-types-values-memory/bytes-runes-strings' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm1-types-values-memory'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm2-pointers-stack-heap', 'M2', 'Pointers, stack, heap', 2 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'values-copy', 'Every assignment is a copy', 0, array[]::text[], 'go/m2-pointers-stack-heap/values-copy' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm2-pointers-stack-heap'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'pointer-receivers', 'Why the method didn''t change anything', 1, array[]::text[], 'go/m2-pointers-stack-heap/pointer-receivers' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm2-pointers-stack-heap'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'escape-analysis', 'Who decides stack or heap', 2, array['escapeAnalysis']::text[], 'go/m2-pointers-stack-heap/escape-analysis' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm2-pointers-stack-heap'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'no-pointer-arithmetic', 'Pointers without arithmetic', 3, array[]::text[], 'go/m2-pointers-stack-heap/no-pointer-arithmetic' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm2-pointers-stack-heap'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm3-slices-maps', 'M3', 'Slices and maps, internals first', 3 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'slice-aliasing', 'Two appends, one backing array', 0, array[]::text[], 'go/m3-slices-maps/slice-aliasing' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm3-slices-maps'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'slicing-shares-memory', 's[1:3] is a window, not a copy', 1, array[]::text[], 'go/m3-slices-maps/slicing-shares-memory' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm3-slices-maps'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'range-copies', 'range hands you a copy', 2, array[]::text[], 'go/m3-slices-maps/range-copies' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm3-slices-maps'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'nil-maps', 'Reading a nil map is fine, writing panics', 3, array[]::text[], 'go/m3-slices-maps/nil-maps' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm3-slices-maps'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'map-order', 'Map order is random on purpose', 4, array[]::text[], 'go/m3-slices-maps/map-order' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm3-slices-maps'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm4-structs-methods', 'M4', 'Structs, methods, composition', 4 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'method-sets', 'Method sets decide what satisfies what', 0, array[]::text[], 'go/m4-structs-methods/method-sets' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm4-structs-methods'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'embedding', 'Embedding is not inheritance', 1, array[]::text[], 'go/m4-structs-methods/embedding' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm4-structs-methods'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm5-interfaces', 'M5', 'Interfaces', 5 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'nil-interface', 'A nil pointer in an interface is not nil', 0, array[]::text[], 'go/m5-interfaces/nil-interface' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm5-interfaces'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'implicit-satisfaction', 'No implements keyword', 1, array[]::text[], 'go/m5-interfaces/implicit-satisfaction' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm5-interfaces'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'io-composition', 'io.Reader and io.Writer compose', 2, array[]::text[], 'go/m5-interfaces/io-composition' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm5-interfaces'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm6-errors', 'M6', 'Errors as values', 6 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'sentinel-vs-typed', 'Sentinel and typed errors', 0, array[]::text[], 'go/m6-errors/sentinel-vs-typed' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm6-errors'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'wrapping', '%w, errors.Is, errors.As', 1, array[]::text[], 'go/m6-errors/wrapping' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm6-errors'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'defer-timing', 'defer evaluates arguments now', 2, array[]::text[], 'go/m6-errors/defer-timing' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm6-errors'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'panic-recover', 'When panic is correct, where recover works', 3, array[]::text[], 'go/m6-errors/panic-recover' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm6-errors'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm7-concurrency-1', 'M7', 'Concurrency I', 7 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'goroutines-waitgroup', 'main doesn''t wait', 0, array['goroutines']::text[], 'go/m7-concurrency-1/goroutines-waitgroup' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm7-concurrency-1'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'channels', 'Unbuffered channels are a handshake', 1, array['goroutines', 'deadlockDetection']::text[], 'go/m7-concurrency-1/channels' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm7-concurrency-1'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'select-close', 'select, close, and range over channels', 2, array['goroutines']::text[], 'go/m7-concurrency-1/select-close' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm7-concurrency-1'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'loopvar', 'The loop variable bug that Go 1.22 removed', 3, array['goroutines', 'languageVersion']::text[], 'go/m7-concurrency-1/loopvar' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm7-concurrency-1'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm8-concurrency-2', 'M8', 'Concurrency II', 8 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'data-races', 'Races and -race', 0, array['raceDetector']::text[], 'go/m8-concurrency-2/data-races' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm8-concurrency-2'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'sync-primitives', 'Mutex, RWMutex, Once, atomics', 1, array['goroutines']::text[], 'go/m8-concurrency-2/sync-primitives' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm8-concurrency-2'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'context', 'context cancellation and timeouts', 2, array['goroutines']::text[], 'go/m8-concurrency-2/context' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm8-concurrency-2'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'worker-pools', 'Worker pools, fan-in, fan-out', 3, array['goroutines']::text[], 'go/m8-concurrency-2/worker-pools' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm8-concurrency-2'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'goroutine-leaks', 'Goroutines that never end', 4, array['goroutines']::text[], 'go/m8-concurrency-2/goroutine-leaks' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm8-concurrency-2'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm9-generics', 'M9', 'Generics', 9 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'type-parameters', 'Type parameters and constraints', 0, array['generics']::text[], 'go/m9-generics/type-parameters' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm9-generics'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'wrong-tool', 'When generics are the wrong tool', 1, array['generics']::text[], 'go/m9-generics/wrong-tool' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm9-generics'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm10-testing-tooling', 'M10', 'Testing and tooling', 10 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'table-tests', 'Table-driven tests and subtests', 0, array[]::text[], 'go/m10-testing-tooling/table-tests' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm10-testing-tooling'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'benchmarks-fuzzing', 'Benchmarks and fuzzing', 1, array['benchmarkTiming', 'fuzzing']::text[], 'go/m10-testing-tooling/benchmarks-fuzzing' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm10-testing-tooling'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'vet-gofmt-modules', 'go vet, gofmt, modules', 2, array[]::text[], 'go/m10-testing-tooling/vet-gofmt-modules' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm10-testing-tooling'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm11-stdlib', 'M11', 'Standard library in anger', 11 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'http-handlers', 'Handlers, muxes, and what ServeHTTP really is', 0, array[]::text[], 'go/m11-stdlib/http-handlers' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm11-stdlib'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'json-tags', 'encoding/json and struct tags', 1, array[]::text[], 'go/m11-stdlib/json-tags' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm11-stdlib'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'time', 'time is harder than it looks', 2, array[]::text[], 'go/m11-stdlib/time' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm11-stdlib'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.modules (track_id, slug, code, title, "order") select id, 'm12-capstone', 'M12', 'Capstone', 12 from public.tracks where slug = 'go'
  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";
insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, 'kv-store', 'KV store with TTL, HTTP API, worker pool, graceful shutdown', 0, array['raceDetector', 'netListen']::text[], 'go/m12-capstone/kv-store' from public.modules m join public.tracks t on t.id = m.track_id where t.slug = 'go' and m.slug = 'm12-capstone'
  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.concepts (slug, title) values ('append-aliasing', 'Append aliasing') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('benchmarks', 'Benchmarks') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('capstone', 'Capstone') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('channel-close', 'Channel close') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('channels', 'Channels') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('closures', 'Closures') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('compiler-pipeline', 'Compiler pipeline') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('context', 'Context') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('conversions', 'Conversions') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('data-races', 'Data races') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('deadlock', 'Deadlock') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('defer-evaluation', 'Defer evaluation') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('embedding', 'Embedding') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('encoding-json', 'Encoding json') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('error-values', 'Error values') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('error-wrapping', 'Error wrapping') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('escape-analysis', 'Escape analysis') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('fuzzing', 'Fuzzing') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('generics', 'Generics') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('goroutine-leaks', 'Goroutine leaks') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('goroutines', 'Goroutines') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('implicit-interfaces', 'Implicit interfaces') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('int-sizing', 'Int sizing') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('integer-division', 'Integer division') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('interface-type-value-pair', 'Interface type value pair') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('io-composition', 'Io composition') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('loopvar-semantics', 'Loopvar semantics') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('map-iteration-order', 'Map iteration order') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('method-receivers', 'Method receivers') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('method-sets', 'Method sets') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('modules', 'Modules') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('net-http', 'Net http') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('nil-map', 'Nil map') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('panic-recover', 'Panic recover') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('pointers', 'Pointers') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('range-copy', 'Range copy') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('runtime', 'Runtime') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('select', 'Select') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('slice-header', 'Slice header') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('slicing-shares-array', 'Slicing shares array') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('small-interfaces', 'Small interfaces') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('static-linking', 'Static linking') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('strings-bytes-runes', 'Strings bytes runes') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('sync-primitives', 'Sync primitives') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('table-tests', 'Table tests') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('time', 'Time') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('toolchain', 'Toolchain') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('tooling', 'Tooling') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('value-semantics', 'Value semantics') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('waitgroup', 'Waitgroup') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('worker-pools', 'Worker pools') on conflict (slug) do update set title = excluded.title;
insert into public.concepts (slug, title) values ('zero-values', 'Zero values') on conflict (slug) do update set title = excluded.title;

insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m0-compiled/go-run-vs-go-build' and c.slug = 'toolchain' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m0-compiled/source-to-machine-code' and c.slug = 'compiler-pipeline' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m0-compiled/runtime-in-every-binary' and c.slug = 'runtime' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m0-compiled/runtime-in-every-binary' and c.slug = 'static-linking' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m1-types-values-memory/zero-values' and c.slug = 'zero-values' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m1-types-values-memory/no-implicit-conversion' and c.slug = 'conversions' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m1-types-values-memory/no-implicit-conversion' and c.slug = 'int-sizing' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m1-types-values-memory/integer-division' and c.slug = 'integer-division' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m1-types-values-memory/bytes-runes-strings' and c.slug = 'strings-bytes-runes' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m2-pointers-stack-heap/values-copy' and c.slug = 'value-semantics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m2-pointers-stack-heap/pointer-receivers' and c.slug = 'value-semantics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m2-pointers-stack-heap/pointer-receivers' and c.slug = 'method-receivers' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m2-pointers-stack-heap/escape-analysis' and c.slug = 'escape-analysis' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m2-pointers-stack-heap/no-pointer-arithmetic' and c.slug = 'pointers' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/slice-aliasing' and c.slug = 'slice-header' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/slice-aliasing' and c.slug = 'append-aliasing' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/slicing-shares-memory' and c.slug = 'slice-header' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/slicing-shares-memory' and c.slug = 'slicing-shares-array' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/range-copies' and c.slug = 'range-copy' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/range-copies' and c.slug = 'value-semantics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/nil-maps' and c.slug = 'nil-map' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m3-slices-maps/map-order' and c.slug = 'map-iteration-order' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m4-structs-methods/method-sets' and c.slug = 'method-receivers' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m4-structs-methods/method-sets' and c.slug = 'method-sets' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m4-structs-methods/embedding' and c.slug = 'embedding' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m5-interfaces/nil-interface' and c.slug = 'interface-type-value-pair' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m5-interfaces/implicit-satisfaction' and c.slug = 'implicit-interfaces' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m5-interfaces/io-composition' and c.slug = 'io-composition' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m5-interfaces/io-composition' and c.slug = 'small-interfaces' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m6-errors/sentinel-vs-typed' and c.slug = 'error-values' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m6-errors/wrapping' and c.slug = 'error-wrapping' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m6-errors/defer-timing' and c.slug = 'defer-evaluation' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m6-errors/panic-recover' and c.slug = 'panic-recover' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/goroutines-waitgroup' and c.slug = 'goroutines' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/goroutines-waitgroup' and c.slug = 'waitgroup' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/channels' and c.slug = 'channels' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/channels' and c.slug = 'deadlock' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/select-close' and c.slug = 'select' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/select-close' and c.slug = 'channel-close' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/loopvar' and c.slug = 'loopvar-semantics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m7-concurrency-1/loopvar' and c.slug = 'closures' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m8-concurrency-2/data-races' and c.slug = 'data-races' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m8-concurrency-2/sync-primitives' and c.slug = 'sync-primitives' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m8-concurrency-2/context' and c.slug = 'context' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m8-concurrency-2/worker-pools' and c.slug = 'worker-pools' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m8-concurrency-2/goroutine-leaks' and c.slug = 'goroutine-leaks' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m9-generics/type-parameters' and c.slug = 'generics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m9-generics/wrong-tool' and c.slug = 'generics' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m10-testing-tooling/table-tests' and c.slug = 'table-tests' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m10-testing-tooling/benchmarks-fuzzing' and c.slug = 'benchmarks' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m10-testing-tooling/benchmarks-fuzzing' and c.slug = 'fuzzing' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m10-testing-tooling/vet-gofmt-modules' and c.slug = 'tooling' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m10-testing-tooling/vet-gofmt-modules' and c.slug = 'modules' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m11-stdlib/http-handlers' and c.slug = 'net-http' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m11-stdlib/json-tags' and c.slug = 'encoding-json' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m11-stdlib/time' and c.slug = 'time' on conflict do nothing;
insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = 'go/m12-capstone/kv-store' and c.slug = 'capstone' on conflict do nothing;

commit;
