// Generates supabase/seed.sql (content tables) from content/go/track.json.
// Content files are the source of truth; the DB copy exists so user rows can
// reference lessons/concepts by foreign key. Idempotent: upserts by slug.
// The track JSON is embedded once and unpacked in SQL, which keeps the seed
// small enough to paste into the Supabase SQL editor.
//   node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const track = JSON.parse(readFileSync(join(root, "content", "go", "track.json"), "utf8"));
const json = JSON.stringify(track);
if (json.includes("$seed$")) throw new Error("track.json contains the dollar-quote tag");

const sql = `-- GENERATED by scripts/gen-seed.mjs from content/go/track.json. Do not edit.
begin;

create temp table _seed on commit drop as select $seed$${json}$seed$::jsonb as j;

insert into public.tracks (slug, title, "order")
select j->>'slug', j->>'title', 1 from _seed
on conflict (slug) do update set title = excluded.title, "order" = excluded."order";

insert into public.modules (track_id, slug, code, title, "order")
select t.id, m.value->>'slug', m.value->>'code', m.value->>'title', (m.ordinality - 1)::int
from _seed, jsonb_array_elements(j->'modules') with ordinality m, public.tracks t
where t.slug = j->>'slug'
on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";

insert into public.lessons (module_id, slug, title, "order", requires, content_ref)
select mo.id, l.value->>'slug', l.value->>'title', (l.ordinality - 1)::int,
       array(select jsonb_array_elements_text(l.value->'requires')),
       'go/' || (m.value->>'slug') || '/' || (l.value->>'slug')
from _seed, jsonb_array_elements(j->'modules') m, jsonb_array_elements(m.value->'lessons') with ordinality l, public.modules mo, public.tracks t
where mo.slug = m.value->>'slug' and mo.track_id = t.id and t.slug = j->>'slug'
on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;

insert into public.concepts (slug, title)
select distinct c, upper(left(replace(c, '-', ' '), 1)) || substr(replace(c, '-', ' '), 2)
from _seed, jsonb_array_elements(j->'modules') m, jsonb_array_elements(m.value->'lessons') l, jsonb_array_elements_text(l.value->'concepts') c
on conflict (slug) do update set title = excluded.title;

insert into public.lesson_concepts (lesson_id, concept_id)
select le.id, co.id
from _seed, jsonb_array_elements(j->'modules') m, jsonb_array_elements(m.value->'lessons') l, jsonb_array_elements_text(l.value->'concepts') c, public.concepts co, public.lessons le
where co.slug = c and le.content_ref = 'go/' || (m.value->>'slug') || '/' || (l.value->>'slug')
on conflict do nothing;

commit;
`;
writeFileSync(join(root, "supabase", "seed.sql"), sql);
console.log(`seed.sql: ${track.modules.length} modules, ${track.modules.reduce((n, m) => n + m.lessons.length, 0)} lessons, ${sql.length} bytes`);
