// Generates supabase/seed.sql (content tables) from content/go/track.json.
// Content files are the source of truth; the DB copy exists so user rows can
// reference lessons/concepts by foreign key. Idempotent: upserts by slug.
//   node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const track = JSON.parse(readFileSync(join(root, "content", "go", "track.json"), "utf8"));
const q = (s) => `'${String(s).replaceAll("'", "''")}'`;
const arr = (xs) => `array[${xs.map(q).join(", ")}]::text[]`;
const humanize = (slug) => slug.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase());

const out = ["-- GENERATED by scripts/gen-seed.mjs from content/go/track.json. Do not edit.", "begin;", ""];
out.push(`insert into public.tracks (slug, title, "order") values (${q(track.slug)}, ${q(track.title)}, 1)`);
out.push(`  on conflict (slug) do update set title = excluded.title, "order" = excluded."order";`, "");

const concepts = new Set();
track.modules.forEach((m, mi) => {
  out.push(
    `insert into public.modules (track_id, slug, code, title, "order") select id, ${q(m.slug)}, ${q(m.code)}, ${q(m.title)}, ${mi} from public.tracks where slug = ${q(track.slug)}`,
    `  on conflict (track_id, slug) do update set code = excluded.code, title = excluded.title, "order" = excluded."order";`,
  );
  m.lessons.forEach((l, li) => {
    l.concepts.forEach((c) => concepts.add(c));
    out.push(
      `insert into public.lessons (module_id, slug, title, "order", requires, content_ref) select m.id, ${q(l.slug)}, ${q(l.title)}, ${li}, ${arr(l.requires)}, ${q(`go/${m.slug}/${l.slug}`)} from public.modules m join public.tracks t on t.id = m.track_id where t.slug = ${q(track.slug)} and m.slug = ${q(m.slug)}`,
      `  on conflict (content_ref) do update set title = excluded.title, "order" = excluded."order", requires = excluded.requires;`,
    );
  });
  out.push("");
});

for (const c of [...concepts].sort()) {
  out.push(`insert into public.concepts (slug, title) values (${q(c)}, ${q(humanize(c))}) on conflict (slug) do update set title = excluded.title;`);
}
out.push("");
for (const m of track.modules) {
  for (const l of m.lessons) {
    for (const c of l.concepts) {
      out.push(
        `insert into public.lesson_concepts (lesson_id, concept_id) select l.id, c.id from public.lessons l, public.concepts c where l.content_ref = ${q(`go/${m.slug}/${l.slug}`)} and c.slug = ${q(c)} on conflict do nothing;`,
      );
    }
  }
}
out.push("", "commit;", "");
writeFileSync(join(root, "supabase", "seed.sql"), out.join("\n"));
console.log(`seed.sql: ${track.modules.length} modules, ${track.modules.reduce((n, m) => n + m.lessons.length, 0)} lessons, ${concepts.size} concepts`);
